@echo off
echo Installing dependencies...
pip install -r requirements.txt

echo Starting MongoDB (if installed)...
start "" mongod

echo Starting FastAPI server...
uvicorn main:app --reload --host 0.0.0.0 --port 8000